config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  devise_for :users
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: 'User'
  belongs_to :follower, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :relationships, foreign_key: :following_id
  has_many :followings, through: :relationships, source: :follower

  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: :follower_id
  has_many :followers, through: :reverse_of_relationships, source: :following

  def is_followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource) 
    user_path(current_user)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!
  def create
    following = current_user.relationships.build(follower_id: params[:user_id])
    following.save
    redirect_to request.referrer || root_path
  end

  def destroy
    following = current_user.relationships.find_by(follower_id: params[:user_id])
    following.destroy
    redirect_to request.referrer || root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.where.not(id: current_user.id)
  end

  def followings
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<main class="mt-5">
  <div class="starter-template text-center">
    <h1>Welcome to my template.</h1>
    <p class="lead">Use this template as a way to quickly start any new project.</p>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FollowApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark p-3">
      <%= link_to root_path, class: "navbar-brand" do %>
        LOGO
      <% end %>
    
      <div class="collapse navbar-collapse" id="navbarsExample03">
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item active">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to "Mypage", user_path(current_user), class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to "Users", users_path, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item active">
              <%= link_to 'Log in', new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <% if flash[:notice] %>
      <div class="alert alert-primary text-center" role="alert"><strong><%= notice %></strong></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger text-center" role="alert"><strong><%= alert %></strong></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/followers.html.erb
<div class="container marketing">
  <div class="row d-flex justify-content-center">
    <div class="col-10 mt-5">
      <h1>FOLLOWERS</h1>
      <table class="table text-center">
        <thead>
          <tr>
            <th>Name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= link_to user_path(user) do %>
                  <%= user.name %>
                <% end %>
              </td>
              <td>
                <% if user != current_user %>
                  <% if user.is_followed_by?(current_user) %>
                    <%=link_to user_relationships_path(user), method: :delete do %>
                      <button type="button" class="btn btn btn-danger">フォロー解除</button>
                    <% end %>
                  <% else %>
                    <%=link_to user_relationships_path(user), method: :post do %>
                      <button type="button" class="btn btn btn-primary">フォロー</button>
                    <% end %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/followings.html.erb
<div class="container marketing">
  <div class="row d-flex justify-content-center">
    <div class="col-10 mt-5">
      <h1>FOLLOWING</h1>
      <table class="table text-center">
        <thead>
          <tr>
            <th>Name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= link_to user_path(user) do %>
                  <%= user.name %>
                <% end %>
              </td>
              <td>
                <% if user != current_user %>
                  <% if user.is_followed_by?(current_user) %>
                    <%=link_to user_relationships_path(user), method: :delete do %>
                      <button type="button" class="btn btn btn-danger">フォロー解除</button>
                    <% end %>
                  <% else %>
                    <%=link_to user_relationships_path(user), method: :post do %>
                      <button type="button" class="btn btn btn-primary">フォロー</button>
                    <% end %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container marketing">
  <div class="row d-flex justify-content-center">
    <div class="col-10 mt-5">
      <table class="table text-center">
        <thead>
          <tr>
            <th>Name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= link_to user_path(user) do %>
                  <%= user.name %>
                <% end %>
              </td>
              <td>
                <% if user.is_followed_by?(current_user) %>
                  <%=link_to user_relationships_path(user), method: :delete do %>
                    <button type="button" class="btn btn btn-danger">フォロー解除</button>
                  <% end %>
                <% else %>
                  <%=link_to user_relationships_path(user), method: :post do %>
                    <button type="button" class="btn btn btn-primary">フォロー</button>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <svg width="80" height="80" class="svg-icon" viewBox="0 0 20 20">
        <path d="M12.075,10.812c1.358-0.853,2.242-2.507,2.242-4.037c0-2.181-1.795-4.618-4.198-4.618S5.921,4.594,5.921,6.775c0,1.53,0.884,3.185,2.242,4.037c-3.222,0.865-5.6,3.807-5.6,7.298c0,0.23,0.189,0.42,0.42,0.42h14.273c0.23,0,0.42-0.189,0.42-0.42C17.676,14.619,15.297,11.677,12.075,10.812 M6.761,6.775c0-2.162,1.773-3.778,3.358-3.778s3.359,1.616,3.359,3.778c0,2.162-1.774,3.778-3.359,3.778S6.761,8.937,6.761,6.775 M3.415,17.69c0.218-3.51,3.142-6.297,6.704-6.297c3.562,0,6.486,2.787,6.705,6.297H3.415z"></path>
      </svg>
      <h1 class="fw-light"><%= @user.name %></h1>
      <p class="text-small"><%= link_to @user.followings.count, followings_user_path(@user) %> フォロー <%= link_to @user.followers.count, followers_user_path(@user) %> フォロワー</p>
      <% if @user == current_user %>
        <p class="lead text-muted">You're currently signed in as <%= current_user.email %></p>
      <% else %>
        <% if @user.is_followed_by?(current_user) %>
          <%= link_to user_relationships_path(@user), method: :delete do %>
            <button class="btn btn-danger">フォロー解除</button>
          <% end %>
        <% else %>
          <%= link_to user_relationships_path(@user), method: :post do %>
            <button class="btn btn-primary">フォロー</button>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</section>